
version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pingram_test
    ports:
      - "5433:5432"  # Use 5433 so it doesn't collide with dev db
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379" # Also use different port if you want test-only redis

  api-test:
    build:
      context: .
      dockerfile: Dockerfile.test  # New Dockerfile just for tests
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/pingram_test
      REDIS_URL: redis://redis:6379
      NODE_ENV: test
    depends_on:
      - postgres
      - redis
    command: npm run test:only # just runs tests, doesn't run server

volumes:
  postgres_test_data:
